### ISSUE TITLE
new version of ubuntu

### ISSUE THREAD

**Issue by TeBear** [nembery/wistar_packer#1]
Need to update wistar-vmware.json to below: 

      "iso_urls": [
        "{{ pwd }}/iso/ubuntu-16.04.2-server-amd64.iso",
        "http://releases.ubuntu.com/16.04/ubuntu-16.04.2-server-amd64.iso"
      ],
      "iso_checksum_type": "sha256",
      "iso_checksum": "0f3086aa44edd38531898b32ee3318540af9c643c27346340deb2f9bc1c3de7e",

**Comment by nembery** [comment]
thanks for the report. This was fixed with commit: b77884b7817c310fc6d1228260953c3457c20939
